app/__init__.py
from flask import Flask

app = Flask(__name__)

app.config.from_object('config')

from app.controllers.problems import bp
app.register_blueprint(bp)

app/controllers/home.py
from flask import Flask, Blueprint, render_template

bp = Blueprint('home', __name__)

@bp.route("/")
def index():
  return render_template('index.html')
  

app/controllers/problems.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for
from app.database.cosmosdb.cosmos import *

bp = Blueprint('problems', __name__)

@bp.route("/")
def index():
  problems = select_all_questions(container)
  return render_template('index.html', problems=problems)
  
@bp.route("/<int:id>/problem", methods=('GET', 'POST') )
def problem(id):
  problem_list = select_problem(container, id)
  temp_ans = problem_list[1]

  if request.method == 'POST':
    answer = select_ans(container, id)
    code = request.form['code']
    if code == "":
      code = temp_ans

    ans_list = answer.splitlines()
    code_list = code.splitlines()

    if len(ans_list) != len(code_list):
      return redirect(url_for('problems.incorrect'))
    else:
      for ans_line, code_line in zip(ans_list, code_list):
        if ans_line != code_line:
          return redirect(url_for('problems.incorrect'))
          
    return redirect(url_for('problems.correct'))

  problem = problem_list[0]
  choice_ans = select_choice_ans(container, id)

  return render_template( 'problem.html', 
                          problem=problem,
                          temp_ans=temp_ans,
                          choice_ans=choice_ans,
                          id=id
                        )

@bp.route("/correct")
def correct():
  return render_template('correct.html')

@bp.route("/incorrect")
def incorrect():
  return render_template('incorrect.html')

app/templates/correct.html
{% extends 'default.html' %}

{% block content %}
<h1 style="font-family: 'DotGothic16', sans-serif;
            position: absolute;
	          top: 50%;
	          left: 50%;
	          transform: translate(-50%, -50%);
	          padding: 0px 0px;
	          text-align: center;
	          width: 900px;
            font-size: 700%;" >
            正解です！！
          </h1>
<iframe allow="autoplay" style="display:none" id="correct_sound"></iframe> 
<script>
  var random_num = Math.floor(Math.random() * 3);
  if (random_num == 0) {
    document.getElementById('correct_sound').src = '../static/music/voice_sample/Seikai1.mp3';
  } else if (random_num == 1) {
    document.getElementById('correct_sound').src = '../static/music/voice_sample/Seikai2.mp3';
  } else if (random_num == 2) {
    document.getElementById('correct_sound').src = '../static/music/voice_sample/Seikai3.mp3';
  }
</script>
{% endblock %}

app/templates/default.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- bootstrap -->
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap" rel="stylesheet">
    <!-- google font -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!-- lib内のライブラリ(cssとjs)をインポート -->
    <link rel="stylesheet" href="../static/lib/codemirror.css">
    <!-- themeでエディタの色変更 -->
    <link rel="stylesheet" href="../static/theme/monokai.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="../static/lib/codemirror.js"></script>
    <script src="../static/mode/python/python.js"></script>
  </head>
  
  <body>
    <!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark p-3">
      <a class="navbar-brand" style="font-family: 'DotGothic16', sans-serif;" href="{{ url_for('problems.index') }}">
        Noise Corder
      </a>
    </nav>

    {% block content %}{% endblock %}

  </body>
</html>

app/templates/incorrect.html
{% extends 'default.html' %}

{% block content %}
<h1 style="font-family: 'DotGothic16', sans-serif;
            position: absolute;
	          top: 50%;
	          left: 50%;
	          transform: translate(-50%, -50%);
	          padding: 0px 0px;
	          text-align: center;
	          width: 900px;
            font-size: 700%;">
            不正解です！！</h1>

<iframe allow="autoplay" style="display:none" id="incorrect_sound"></iframe> 
<script>
  var random_num = Math.floor(Math.random() * 2);
  if (random_num == 0) {
    document.getElementById('incorrect_sound').src = '../static/music/voice_sample/Huseikai1.mp3';
  } else if (random_num == 1) {
    document.getElementById('incorrect_sound').src = '../static/music/voice_sample/Huseikai2.mp3';
  }
</script>
{% endblock %}

app/templates/index.html
{% extends 'default.html' %}

{% block content %}
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" style="font-family: 'DotGothic16', sans-serif;" href="#"><b>問題一覧</b></a>
  </div>
</nav>
  <table class="table">
  <thead>
    <tr>
      <th scope="col" style="font-family: 'DotGothic16', sans-serif;">#</th>
      <th scope="col" style="font-family: 'DotGothic16', sans-serif;">問題名</th>
    </tr>
  </thead>
  <tbody>
    {% for problem in problems %}
    <tr>
      <th scope="row" style="font-family: 'DotGothic16', sans-serif;">{{ loop.index }}</th>
      <td>
        <a href="{{ url_for('problems.problem', id=loop.index|string) }}" style="font-family: 'DotGothic16', sans-serif;">{{ problem }}<br></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
  
  <iframe src=path allow="autoplay" style="display:none" id="opening_audio1"></iframe> 
  <script>
    const btn_play = document.getElementById("btn_play");
    const btn_pause = document.getElementById("btn_pause");
    const audioElement = document.querySelector("audio");

    btn_play.addEventListener("click", e => {
      audioElement.play();
    });

    btn_pause.addEventListener("click", e => {
      audioElement.pause();
    });
  </script>

  <iframe allow="autoplay" style="display:none" id="opening_audio"></iframe> 
  <script>
    var random_num = Math.floor(Math.random() * 2);
    if (random_num == 0) {
      document.getElementById('opening_audio').src = '../static/music/voice_sample/Opening1.mp3';
    } else if (random_num == 1) {
      document.getElementById('opening_audio').src = '../static/music/voice_sample/Opening2.mp3';
    }
  </script>
{% endblock %}

app/templates/mode/python/index.html
<!doctype html>

<title>CodeMirror: Python mode</title>
<meta charset="utf-8"/>
<link rel=stylesheet href="../../doc/docs.css">

<link rel="stylesheet" href="../../lib/codemirror.css">
<script src="../../lib/codemirror.js"></script>
<script src="../../addon/edit/matchbrackets.js"></script>
<script src="python.js"></script>
<style>.CodeMirror {border-top: 1px solid black; border-bottom: 1px solid black;}</style>
<div id=nav>
  <a href="https://codemirror.net"><h1>CodeMirror</h1><img id=logo src="../../doc/logo.png" alt=""></a>

  <ul>
    <li><a href="../../index.html">Home</a>
    <li><a href="../../doc/manual.html">Manual</a>
    <li><a href="https://github.com/codemirror/codemirror">Code</a>
  </ul>
  <ul>
    <li><a href="../index.html">Language modes</a>
    <li><a class=active href="#">Python</a>
  </ul>
</div>

<article>
<h2>Python mode</h2>

    <div><textarea id="code" name="code">
# Literals
1234
0.0e101
.123
0b01010011100
0o01234567
0x0987654321abcdef
7
2147483647
3L
79228162514264337593543950336L
0x100000000L
79228162514264337593543950336
0xdeadbeef
3.14j
10.j
10j
.001j
1e100j
3.14e-10j


# String Literals
'For\''
"God\""
"""so loved
the world"""
'''that he gave
his only begotten\' '''
'that whosoever believeth \
in him'
''

# Identifiers
__a__
a.b
a.b.c

#Unicode identifiers on Python3
# a = x\ddot
a⃗ = ẍ
# a = v\dot
a⃗ = v̇

#F\vec = m \cdot a\vec
F⃗ = m•a⃗ 

# Operators
+ - * / % & | ^ ~ < >
== != <= >= <> << >> // **
and or not in is

#infix matrix multiplication operator (PEP 465)
A @ B

# Delimiters
() [] {} , : ` = ; @ .  # Note that @ and . require the proper context on Python 2.
+= -= *= /= %= &= |= ^=
//= >>= <<= **=

# Keywords
as assert break class continue def del elif else except
finally for from global if import lambda pass raise
return try while with yield

# Python 2 Keywords (otherwise Identifiers)
exec print

# Python 3 Keywords (otherwise Identifiers)
nonlocal

# Types
bool classmethod complex dict enumerate float frozenset int list object
property reversed set slice staticmethod str super tuple type

# Python 2 Types (otherwise Identifiers)
basestring buffer file long unicode xrange

# Python 3 Types (otherwise Identifiers)
bytearray bytes filter map memoryview open range zip

# Some Example code
import os
from package import ParentClass

@nonsenseDecorator
def doesNothing():
    pass

class ExampleClass(ParentClass):
    @staticmethod
    def example(inputStr):
        a = list(inputStr)
        a.reverse()
        return ''.join(a)

    def __init__(self, mixin = 'Hello'):
        self.mixin = mixin

# Python 3.6 f-strings (https://www.python.org/dev/peps/pep-0498/)
f'My name is {name}, my age next year is {age+1}, my anniversary is {anniversary:%A, %B %d, %Y}.'
f'He said his name is {name!r}.'
f"""He said his name is {name!r}."""
f'{"quoted string"}'
f'{{ {4*10} }}'
f'This is an error }'
f'This is ok }}'
fr'x={4*10}\n'
</textarea></div>


<h2>Cython mode</h2>

<div><textarea id="code-cython" name="code-cython">

import numpy as np
cimport cython
from libc.math cimport sqrt

@cython.boundscheck(False)
@cython.wraparound(False)
def pairwise_cython(double[:, ::1] X):
    cdef int M = X.shape[0]
    cdef int N = X.shape[1]
    cdef double tmp, d
    cdef double[:, ::1] D = np.empty((M, M), dtype=np.float64)
    for i in range(M):
        for j in range(M):
            d = 0.0
            for k in range(N):
                tmp = X[i, k] - X[j, k]
                d += tmp * tmp
            D[i, j] = sqrt(d)
    return np.asarray(D)

</textarea></div>

    <script>
      var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
        mode: {name: "python",
               version: 3,
               singleLineStringErrors: false},
        lineNumbers: true,
        indentUnit: 4,
        matchBrackets: true
    });

    CodeMirror.fromTextArea(document.getElementById("code-cython"), {
        mode: {name: "text/x-cython",
               version: 2,
               singleLineStringErrors: false},
        lineNumbers: true,
        indentUnit: 4,
        matchBrackets: true
      });
    </script>
    <h2>Configuration Options for Python mode:</h2>
    <ul>
      <li>version - 2/3 - The version of Python to recognize.  Default is 3.</li>
      <li>singleLineStringErrors - true/false - If you have a single-line string that is not terminated at the end of the line, this will show subsequent lines as errors if true, otherwise it will consider the newline as the end of the string. Default is false.</li>
      <li>hangingIndent - int - If you want to write long arguments to a function starting on a new line, how much that line should be indented. Defaults to one normal indentation unit.</li>
    </ul>
    <h2>Advanced Configuration Options:</h2>
    <p>Useful for superset of python syntax like Enthought enaml, IPython magics and  questionmark help</p>
    <ul>
      <li>singleOperators - RegEx - Regular Expression for single operator matching,  default : <pre>^[\\+\\-\\*/%&amp;|\\^~&lt;&gt;!]</pre> including <pre>@</pre> on Python 3</li>
      <li>singleDelimiters - RegEx - Regular Expression for single delimiter matching, default :  <pre>^[\\(\\)\\[\\]\\{\\}@,:`=;\\.]</pre></li>
      <li>doubleOperators - RegEx - Regular Expression for double operators matching, default : <pre>^((==)|(!=)|(&lt;=)|(&gt;=)|(&lt;&gt;)|(&lt;&lt;)|(&gt;&gt;)|(//)|(\\*\\*))</pre></li>
      <li>doubleDelimiters - RegEx - Regular Expression for double delimiters matching, default : <pre>^((\\+=)|(\\-=)|(\\*=)|(%=)|(/=)|(&amp;=)|(\\|=)|(\\^=))</pre></li>
      <li>tripleDelimiters - RegEx - Regular Expression for triple delimiters matching, default : <pre>^((//=)|(&gt;&gt;=)|(&lt;&lt;=)|(\\*\\*=))</pre></li>
      <li>identifiers - RegEx - Regular Expression for identifier, default : <pre>^[_A-Za-z][_A-Za-z0-9]*</pre> on Python 2 and <pre>^[_A-Za-z\u00A1-\uFFFF][_A-Za-z0-9\u00A1-\uFFFF]*</pre> on Python 3.</li>
      <li>extra_keywords - list of string - List of extra words ton consider as keywords</li>
      <li>extra_builtins - list of string - List of extra words ton consider as builtins</li>
    </ul>


    <p><strong>MIME types defined:</strong> <code>text/x-python</code> and <code>text/x-cython</code>.</p>
  </article>

app/templates/problem.html
{% extends 'default.html' %}

{% block content %}
<h2 class="m-2" style="font-family: 'DotGothic16', sans-serif;">
  <b>問題文</b>
</h2>
<hr>
<p class="m-2" style="font-family: 'DotGothic16', sans-serif;">{{ problem }}</p>
<p id="ahi" style="visibility:hidden">{{ temp_ans }}</p>
<p id="fuga" style="visibility:hidden">{{ id }}</p>

<script id=hoge>
  var temp_ans = document.getElementById("ahi").textContent
  console.log(temp_ans);
  var code = "";
  console.log(code);
  var editor = CodeMirror(document.body, {
    value: temp_ans,
    lineNumbers: true,
    theme: 'monokai custom',
    mode: 'python'
  }).on('change', after_editor => {
    code = after_editor.getValue();
    var val = document.getElementById('form');
    val.value = code;
    console.log(val)
  });
</script>
<br>
<h2 class="m-2" style="font-family: 'DotGothic16', sans-serif;">
  <b>選択肢</b>
</h2>
<div class="container">
  <div class="row justify-content-md-center">
    {% for choice in choice_ans %}
      <div class="col-sm">
        <h5 class="text-center" style="font-family: 'DotGothic16', sans-serif;">{{ choice }}</h5>
      </div>
    {% endfor %}
  </div>
</div>
<br>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-lg-2">
      <form action="/" method="get">
        <input class="btn btn-danger" type="submit" value='戻る'>
      </form>
    </div>
    <div class="col col-lg-2"></div>
    <div class="col col-lg-2">
      <form method="POST">
        <input type="hidden" id="form" name="code" value="">
        <!-- ボタンを押したら、request.form[code]つまり、エディタの中身が返される。 -->
        <input class="btn btn-primary" id="btn" type="submit" value='提出'/>
      </form>
    </div>
  </div>
</div>

<audio id="type" src="../static/music/voice_sample/Muda_short.mp3" type="audio/meg"></audio>
  
<script>
  const audioType = document.getElementById("type");
  window.onkeydown = function(e){
    audioType.play();
  };
</script>

<iframe allow="autoplay" style="display:none" id="question_audio"></iframe> 
<script>
  var question_num = document.getElementById("fuga").textContent;
  var random_num = Math.floor(Math.random() * 3);
  console.log(question_num);
  if (question_num == 1 && random_num == 1) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q1miss.mp3';
  } else if (question_num == 1 && (random_num == 2 || random_num || 3)) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q1.mp3';
  } else if (question_num == 2) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q2.mp3';
  }  else if (question_num == 3) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q3.mp3';
  }  else if (question_num == 4) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q4.mp3';
  }  else if (question_num == 5) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q5.mp3';
  }  else if (question_num == 6 && random_num == 1) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q6miss.mp3';
  } else if (question_num == 6 && (random_num == 2 || random_num == 3)) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q6.mp3';
  } else if (question_num == 7) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q7.mp3';
  }  else if (question_num == 8) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q8.mp3';
  }  else if (question_num == 9) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q9.mp3';
  }  else if (question_num == 10) {
    document.getElementById('question_audio').src = '../static/music/voice_sample/q10.mp3';
  }
</script>

{% endblock %}

app/templates/result.html
{% extends 'default.html' %}

{% block content %}
<h1>結果ハッピョーーーーう！！</h1>
{% endblock %}